
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"  # Gunicorn 运行的端口
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=RehabilitationManager.settings
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A RehabilitationManager worker --loglevel=info
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=RehabilitationManager.settings
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A RehabilitationManager beat --loglevel=info
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=RehabilitationManager.settings
      - CELERY_BROKER_URL=redis://redis:6379/0

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: srrCOPD
      MYSQL_USER: zjubj
      MYSQL_PASSWORD: Data@base0
      MYSQL_ROOT_PASSWORD: database
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Nginx 监听的端口
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static  # 静态文件目录
    depends_on:
      - web