# Generated by Django 5.2 on 2025-04-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LimbAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.CharField(max_length=100)),
                ("id_card", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("isUploadByDoctor", models.BooleanField(default=True)),
                ("limbStatus", models.CharField(blank=True, max_length=100, null=True)),
                ("limbStatusUploadTime", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PEFAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.CharField(max_length=100)),
                ("id_card", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("isUploadByDoctor", models.BooleanField(default=True)),
                ("PEF", models.FloatField(blank=True, null=True)),
                ("PEFUploadTime", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RespiratoryAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.CharField(max_length=100)),
                ("id_card", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("isUploadByDoctor", models.BooleanField(default=True)),
                ("MEP", models.FloatField(blank=True, null=True)),
                ("MIP", models.FloatField(blank=True, null=True)),
                ("RespiratoryUploadTime", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StepAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.CharField(max_length=100)),
                ("id_card", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("isUploadByDoctor", models.BooleanField(default=True)),
                ("MWT", models.FloatField(blank=True, null=True)),
                ("STEP", models.IntegerField(blank=True, null=True)),
                ("STEPUploadTime", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SwallowAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.CharField(max_length=100)),
                ("id_card", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("isUploadByDoctor", models.BooleanField(default=True)),
                (
                    "swallowStatus",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "swallowStatusUploadTime",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TCEAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.CharField(max_length=100)),
                ("id_card", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("isUploadByDoctor", models.BooleanField(default=True)),
                ("TCE", models.FloatField(blank=True, null=True)),
                ("TCEUploadTime", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
