# Generated by Django 4.1 on 2024-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('authorities', models.CharField(blank=True, help_text='权限', max_length=200, null=True, verbose_name='权限')),
                ('tel', models.CharField(blank=True, help_text='电话号码', max_length=200, null=True, verbose_name='电话号码')),
                ('email', models.CharField(blank=True, help_text='邮箱', max_length=200, null=True, verbose_name='邮箱')),
                ('desc', models.CharField(blank=True, help_text='描述', max_length=200, null=True, verbose_name='描述')),
            ],
        ),
    ]
