# Generated by Django 4.1 on 2024-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotionList',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False, verbose_name='动作ID')),
                ('name', models.CharField(max_length=100, verbose_name='动作名称')),
                ('category', models.CharField(max_length=50, verbose_name='动作分类')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('weekly_training_count', models.IntegerField(default=7, verbose_name='每周训练次数')),
                ('daily_training_count', models.IntegerField(default=2, verbose_name='每日训练次数')),
                ('sets_per_session', models.IntegerField(default=5, verbose_name='每次训练组数')),
                ('reps_per_set', models.IntegerField(default=6, verbose_name='每组训练个数')),
                ('training_method', models.CharField(default='时长', max_length=50, verbose_name='单一动作训练方式')),
                ('intensity', models.CharField(blank=True, max_length=50, null=True, verbose_name='动作强度')),
            ],
            options={
                'verbose_name': '运动列表',
                'verbose_name_plural': '运动列表',
            },
        ),
        migrations.CreateModel(
            name='MotionPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=100, verbose_name='医生')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('limbPrescription', models.JSONField(default=list, verbose_name='四肢处方')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('pefPrescription', models.JSONField(default=list, verbose_name='PEF处方')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('respiratoryPrescription', models.JSONField(default=list, verbose_name='呼吸处方')),
                ('swallowPrescription', models.JSONField(default=list, verbose_name='吞咽处方')),
                ('tcePrescription', models.JSONField(default=list, verbose_name='TCE处方')),
                ('upload_time', models.DateTimeField(verbose_name='上传时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '处方详情',
                'verbose_name_plural': '处方详情',
            },
        ),
    ]
