# Generated by Django 4.1 on 2025-01-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionlist',
            name='urls',
            field=models.URLField(blank=True, null=True, verbose_name='视频链接'),
        ),
    ]
