# Generated by Django 4.1 on 2025-01-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_motionlist_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionlist',
            name='duration',
            field=models.IntegerField(default=10, verbose_name='持续时间'),
        ),
    ]
