# Generated by Django 4.1 on 2025-01-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_motionlist_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionAudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='音频名称')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('oss_url', models.URLField(verbose_name='OSS URL')),
            ],
            options={
                'verbose_name': '音频列表',
                'verbose_name_plural': '音频列表',
            },
        ),
    ]
