# Generated by Django 4.1 on 2025-02-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_motionaudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('doctor', models.CharField(max_length=100, verbose_name='医生')),
                ('training_content', models.TextField(verbose_name='训练内容')),
                ('submission_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '运动数据',
                'verbose_name_plural': '运动数据',
            },
        ),
    ]
