# Generated by Django 4.1 on 2025-02-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_alter_exerciserecord_training_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionlist',
            name='applicability',
            field=models.CharField(default=None, max_length=100, verbose_name='适用性'),
        ),
        migrations.AddField(
            model_name='motionlist',
            name='details',
            field=models.JSONField(default=None, verbose_name='详细信息'),
        ),
        migrations.AddField(
            model_name='motionlist',
            name='object',
            field=models.CharField(default=None, max_length=100, verbose_name='对象'),
        ),
        migrations.AddField(
            model_name='motionlist',
            name='purpose',
            field=models.CharField(default=None, max_length=100, verbose_name='目的'),
        ),
    ]
