# Generated by Django 4.1 on 2025-02-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0007_motionlist_applicability_motionlist_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionlist',
            name='duration',
            field=models.CharField(default=None, max_length=50, verbose_name='持续时间'),
        ),
    ]
