# Generated by Django 4.1 on 2025-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0008_alter_motionlist_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionlist',
            name='details',
            field=models.TextField(default=None, verbose_name='详细信息'),
        ),
    ]
