# Generated by Django 5.2 on 2025-04-21 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IDcard", models.CharField(max_length=18, unique=True)),
                ("hospital", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=128)),
                ("phone", models.CharField(max_length=15)),
                ("sex", models.CharField(default="男", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="PatientFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.CharField(max_length=255)),
                ("id_card", models.CharField(max_length=18)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("sex", models.CharField(default=None, max_length=10)),
                ("birth", models.DateField(default=datetime.date(1960, 1, 1))),
                ("height", models.FloatField(default=None)),
                ("weight", models.FloatField(default=None)),
                ("waistline", models.FloatField(default=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("followUpTime", models.DateTimeField(default=None, null=True)),
                ("isActive", models.BooleanField(default=True)),
                ("isFinished", models.BooleanField(default=False)),
                ("deactivateTime", models.DateTimeField(default=None, null=True)),
                ("isEnded", models.BooleanField(default=False)),
                ("endedTime", models.DateTimeField(default=None, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("diseases", models.CharField(default="none", max_length=255)),
                ("followTimes", models.IntegerField(default=0)),
                ("followUpType", models.CharField(default="普通随访", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PatientPrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "swallowStatusPrescription",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "MepAndMipPrescription",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "limbStatusPrescription",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "PEFPrescription",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "TCEPrescription",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "MwtAndStepPrescription",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("doctor", models.CharField(max_length=255)),
                ("id_card", models.CharField(max_length=18)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("uploadtime", models.DateTimeField(auto_now_add=True)),
                ("isActive", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("sex", models.CharField(default=None, max_length=10)),
                ("birth", models.DateField(default=datetime.date(1960, 1, 1))),
                ("height", models.FloatField(default=None)),
                ("weight", models.FloatField(default=None)),
                ("waistline", models.FloatField(default=None)),
                ("diseases", models.CharField(default="none", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_card", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=10)),
                ("birth", models.DateField()),
                ("phone", models.CharField(max_length=15)),
                ("education", models.CharField(max_length=50)),
                ("marital_status", models.CharField(max_length=20)),
                ("nation", models.CharField(max_length=50)),
                ("occupation", models.CharField(max_length=50)),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("waistline", models.FloatField()),
                ("diseases", models.CharField(default="none", max_length=255)),
                ("doctor", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=128)),
                ("is_verified", models.BooleanField(default=False)),
                ("has_prescription", models.BooleanField(default=False)),
                (
                    "openid",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "unionid",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
