# Generated by Django 5.2 on 2025-04-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="openid",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="unionid",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
