# Generated by Django 5.2 on 2025-04-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientBestPEFRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_card", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("doctor", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("bestpefInput", models.FloatField()),
                ("currentTime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PatientPEFRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_card", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("doctor", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("pefValue", models.FloatField()),
                ("dateText", models.CharField(max_length=100)),
                ("currentTime", models.DateTimeField()),
            ],
        ),
    ]
