# Generated by Django 5.2 on 2025-04-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("id_card", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("doctor", models.CharField(default="无", max_length=255)),
                ("followUpEffectiveness", models.CharField(max_length=255)),
                ("ineffectivenessReason", models.CharField(max_length=255)),
                ("qualityOfLife", models.CharField(max_length=255)),
                ("physicalCondition", models.CharField(max_length=255)),
                ("psychologicalCondition", models.CharField(max_length=255)),
                ("medicationAdherence", models.CharField(max_length=255)),
                ("exacerbations", models.CharField(max_length=255)),
                ("acuteExacerbations", models.CharField(max_length=255)),
                ("newDiscomfort", models.CharField(max_length=255)),
                ("newSymptoms", models.CharField(max_length=255)),
                ("followUpReason", models.CharField(max_length=255)),
                ("reasonDetail", models.TextField()),
                ("followUpTime", models.DateTimeField()),
            ],
        ),
    ]
